# Change these first
owner: copypastemaster # Your GitHub organization or username, where this repository lives
repo: legendary-fortnight # The name of this repository

sites:
    #  Frontend
  - name: ReachLink Production Frontend
    url: https://app1.reachlink.com
  - name: ReachLink Staging Frontend
    url: https://staging.reachlink.com
  - name: ReachLink Dev Frontend
    url: https://reachlink-frontend-dev-c13e719bdbb8.herokuapp.com

    #  Backend
  - name: ReachLink Production Backend
    url: $PROD_HEALTH_ENDPOINT
  - name: ReachLink Staging Backend
    url: $STAGING_HEALTH_ENDPOINT
  - name: ReachLink Dev Backend
    url: $DEV_HEALTH_ENDPOINT

    #  Redis
  - name: Production redis
    url: $PROD_HEALTH_REDIS
  - name: Staging redis
    url: $STAGING_HEALTH_REDIS
  - name: Dev redis
    url: $DEV_HEALTH_REDIS

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: staging.reachlink.com
  # faviconSvg: https://raw.githubusercontent.com/reachlink/reachlink-frontend/public/favicon/Reachlink_Favicon.svg
  baseUrl: /legendary-fortnight
  # logoUrl: https://raw.githubusercontent.com/reachlink/reachlink-frontend/public/favicon/Reachlink_Favicon.svg
  name: ReachLink Health
  introTitle: "**ReachLink System Health**" 
  introMessage: ReachLink monitoring for backend, frontend, and redis services.
  navbar:
    - title: Status
      href: /legendary-fortnight
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
